/**
 * AWS Pricing Data Module
 * Loads pricing data from JSON file generated by Infracost API
 * 
 * Supported resources reference: https://www.infracost.io/docs/supported_resources/aws/
 */

import * as fs from 'fs';
import * as path from 'path';

export const HOURS_PER_MONTH = 730;
export const DEFAULT_REGION = 'us-east-1';

// Pricing data structure from JSON file - comprehensive coverage of Infracost-supported resources
export interface AWSpricingData {
  region: string;
  lastUpdated: string;
  
  // Compute
  ec2: {
    instances: Record<string, number>;
    hosts: Record<string, number>;
  };
  ebs: {
    volumes: Record<string, number>;
    iops: Record<string, number>;
    throughput: Record<string, number>;
    snapshots: number;
  };
  
  // Database
  rds: {
    instances: Record<string, Record<string, number>>;
    storage: Record<string, number>;
    iops: number;
  };
  aurora: {
    instances: Record<string, number>;
    storage: number;
    ioRequests: number;
    backtrackChanges: number;
  };
  elasticache: {
    nodes: Record<string, number>;
  };
  dynamodb: {
    readCapacity: number;
    writeCapacity: number;
    onDemandRead: number;
    onDemandWrite: number;
    storage: number;
    globalTables: number;
    streams: number;
  };
  neptune: {
    instances: Record<string, number>;
    storage: number;
    ioRequests: number;
  };
  documentdb: {
    instances: Record<string, number>;
    storage: number;
    ioRequests: number;
  };
  redshift: {
    instances: Record<string, number>;
  };
  
  // Networking
  natGateway: {
    hourly: number;
    perGB: number;
  };
  loadBalancer: {
    alb: { hourly: number; lcuHourly: number };
    nlb: { hourly: number; lcuHourly: number };
    glb: { hourly: number; lcuHourly: number };
    clb: { hourly: number };
  };
  vpcEndpoint: {
    interfaceHourly: number;
    gatewayLoadBalancerHourly: number;
    dataProcessed: number;
  };
  vpnConnection: {
    hourly: number;
    transitGatewayAttachment: number;
    clientVpn: {
      endpointHourly: number;
      connectionHourly: number;
    };
  };
  transitGateway: {
    hourly: number;
    dataProcessed: number;
    peering: number;
  };
  trafficMirror: {
    sessionHourly: number;
  };
  directConnect: {
    portHours: Record<string, number>;
    dataTransfer: number;
  };
  globalAccelerator: {
    hourly: number;
    dataTransfer: number;
  };
  
  // Containers & Orchestration
  eks: {
    clusterHourly: number;
    fargateVcpuHourly?: number;
    fargateMemoryGBHourly?: number;
  };
  ecs: {
    fargateVcpuHourly: number;
    fargateMemoryGBHourly: number;
  };
  ecr: {
    storage: number;
  };
  
  // Serverless
  lambda: {
    requests: number;
    duration: number;
    provisionedConcurrency: number;
  };
  apiGateway: {
    rest: number;
    http: number;
    websocket: number;
    websocketMessages: number;
  };
  stepFunctions: {
    standard: number;
    express: number;
  };
  
  // Storage
  s3: {
    standardStorage: number;
    standardIAStorage: number;
    oneZoneIAStorage: number;
    glacierStorage: number;
    glacierDeepArchive: number;
    intelligentTiering: number;
    requests: {
      put: number;
      get: number;
      lifecycle: number;
    };
  };
  efs: {
    standard: number;
    ia: number;
    provisionedThroughput: number;
  };
  fsx: {
    lustre: number;
    windows: number;
    ontap: number;
    openzfs: number;
  };
  backup: {
    storage: number;
    restoreStorage: number;
  };
  
  // Search & Analytics
  opensearch: {
    instances: Record<string, number>;
    storage: number;
    ultrawarmStorage: number;
  };
  elasticsearch: {
    instances: Record<string, number>;
  };
  kinesis: {
    shardHourly: number;
    payloadUnit: number;
    extendedRetention: number;
    enhancedFanout: number;
  };
  kinesisFirehose: {
    dataIngested: number;
    formatConversion: number;
  };
  glue: {
    dpuHour: number;
    crawlerDpuHour: number;
    catalogStorage: number;
    catalogRequests: number;
  };
  athena: {
    dataScanned: number;
  };
  
  // Messaging
  sqs: {
    standard: number;
    fifo: number;
  };
  sns: {
    publish: number;
    deliveries: {
      http: number;
      email: number;
      sms: number;
      lambda: number;
      sqs: number;
    };
  };
  eventbridge: {
    customEvents: number;
    partnerEvents: number;
    archiveProcessed: number;
    schemaDiscovery: number;
  };
  mq: {
    instanceHourly: Record<string, number>;
    storage: number;
  };
  msk: {
    instanceHourly: Record<string, number>;
    storage: number;
  };
  
  // Directory Service
  directoryService: {
    simpleAD: {
      small: number;
      large: number;
    };
    microsoftAD: {
      standard: number;
      enterprise: number;
    };
  };
  
  // MWAA
  mwaa: {
    environment: Record<string, number>; // mw1.small, medium, large
  };
  
  // Kinesis Analytics
  kinesisAnalytics: {
    kpuHourly: number;
    storage: number;
  };
  
  // Security & Identity
  ssm: {
    parameter: {
      standard: number;
      advanced: number;
      apiCalls: number;
    };
    activation: {
      standard: number;
      advanced: number;
    };
  };
  secretsManager: {
    secret: number;
    apiCalls: number;
  };
  kms: {
    key: number;
    requests: number;
  };
  acm: {
    privateCertificate: number;
  };
  waf: {
    webACL: number;
    rule: number;
    requests: number;
  };
  guardDuty: {
    events: number;
    s3Events: number;
    eksEvents: number;
  };
  macie: {
    bucketEvaluated: number;
    dataScanned: number;
  };
  
  // Management & Monitoring
  cloudwatch: {
    metrics: number;
    alarmStandard: number;
    alarmHighRes: number;
    alarmAnomaly: number;
    alarmComposite: number;
    dashboards: number;
    logsIngestion: number;
    logsStorage: number;
    logsInsightsQueries: number;
    contributorInsightsRules: number;
    contributorInsightsEvents: number;
  };
  cloudtrail: {
    managementEvents: number;
    dataEvents: number;
    insightsEvents: number;
  };
  config: {
    configItems: number;
    rules: number;
    conformancePackRules: number;
  };
  
  // Developer Tools
  codebuild: {
    linuxSmall: number;
    linuxMedium: number;
    linuxLarge: number;
    linux2xlarge: number;
    armLarge: number;
    gpuLarge: number;
    windowsMedium: number;
    windowsLarge: number;
  };
  codepipeline: {
    activePipeline: number;
    trialPipelines: number;
  };
  
  // Content Delivery
  cloudfront: {
    dataTransfer: Record<string, number>;
    requests: {
      http: number;
      https: number;
    };
    invalidations: number;
    ssl: number;
    originShield: number;
    realtimeLogs: number;
    functions: number;
  };
  
  // DNS
  route53: {
    hostedZone: number;
    queries: number;
    healthChecks: {
      basic: number;
      https: number;
      string: number;
      fast: number;
    };
    resolverEndpoint: number;
    resolverQueries: number;
  };
  
  // Machine Learning
  sagemaker: {
    notebookInstances: Record<string, number>;
    trainingInstances: Record<string, number>;
    endpointInstances: Record<string, number>;
  };
  
  // Transfer & Migration
  transferFamily: {
    protocols: number;
    dataProcessed: number;
  };
  dms: {
    instances: Record<string, number>;
  };
  
  // IoT
  iot: {
    connectivityMinutes: number;
    messages: number;
    ruleEngineActions: number;
  };
  
  // Other services
  lightsail: {
    instances: Record<string, number>;
  };
  beanstalk: {
    // Environment cost is based on underlying resources
  };
  
  // Backwards compatibility
  fargate: {
    vcpuHourly: number;
    memoryGBHourly: number;
  };
  
  // Generic other pricing
  other: {
    // Keeping for backwards compatibility - these are now in specific sections above
    dynamodb?: {
      readCapacity: number;
      writeCapacity: number;
      onDemandRead: number;
      onDemandWrite: number;
      storage: number;
    };
    s3?: {
      standardStorage: number;
      standardIAStorage: number;
      glacierStorage: number;
    };
    apiGateway?: {
      rest: number;
      http: number;
      websocket: number;
    };
    sqs?: {
      standard: number;
      fifo: number;
    };
    sns?: {
      publish: number;
    };
    cloudwatch?: {
      metrics: number;
      alarmStandard: number;
      alarmHighRes: number;
      dashboards: number;
      logsIngestion: number;
      logsStorage: number;
    };
    secretsManager?: {
      secret: number;
      apiCalls: number;
    };
    kms?: {
      key: number;
      requests: number;
    };
    stepFunctions?: {
      standard: number;
      express: number;
    };
    route53?: {
      hostedZone: number;
      queries: number;
    };
    vpcEndpoint?: {
      hourly: number;
      dataProcessed: number;
    };
    cognito?: {
      mau: number;
    };
    eventBridge?: {
      customEvents: number;
    };
    kinesis?: {
      shardHourly: number;
      payloadUnit: number;
    };
    efs?: {
      standard: number;
      ia: number;
    };
    ecr?: {
      storage: number;
    };
    waf?: {
      webACL: number;
      rule: number;
      requests: number;
    };
    glue?: {
      dpuHour: number;
    };
    athena?: {
      dataScanned: number;
    };
  };
}

// Default fallback pricing data (us-east-1 baseline)
const DEFAULT_PRICING: AWSpricingData = {
  region: 'us-east-1',
  lastUpdated: new Date().toISOString(),
  
  // EC2
  ec2: {
    instances: {
      't3.nano': 0.0052, 't3.micro': 0.0104, 't3.small': 0.0208, 't3.medium': 0.0416,
      't3.large': 0.0832, 't3.xlarge': 0.1664, 't3.2xlarge': 0.3328,
      't3a.nano': 0.0047, 't3a.micro': 0.0094, 't3a.small': 0.0188, 't3a.medium': 0.0376,
      'm5.large': 0.096, 'm5.xlarge': 0.192, 'm5.2xlarge': 0.384, 'm5.4xlarge': 0.768,
      'm6i.large': 0.096, 'm6i.xlarge': 0.192,
      'c5.large': 0.085, 'c5.xlarge': 0.17, 'c6i.large': 0.085,
      'r5.large': 0.126, 'r5.xlarge': 0.252,
    },
    hosts: {
      'm5.large': 0.106, // ~10% markup
      'c5.large': 0.094,
      'r5.large': 0.139,
    },
  },
  
  // EBS
  ebs: {
    volumes: { 'gp2': 0.10, 'gp3': 0.08, 'io1': 0.125, 'io2': 0.125, 'st1': 0.045, 'sc1': 0.015, 'standard': 0.05 },
    iops: { 'io1': 0.065, 'io2': 0.065, 'gp3': 0.005 },
    throughput: { 'gp3': 0.04 },
    snapshots: 0.05,
  },
  
  // RDS
  rds: {
    instances: {
      'mysql': { 'db.t3.micro': 0.017, 'db.t3.small': 0.034, 'db.t3.medium': 0.068, 'db.m5.large': 0.171, 'db.r5.large': 0.24 },
      'postgresql': { 'db.t3.micro': 0.018, 'db.t3.small': 0.036, 'db.t3.medium': 0.072, 'db.m5.large': 0.178, 'db.r5.large': 0.25 },
      'mariadb': { 'db.t3.micro': 0.017, 'db.t3.small': 0.034, 'db.t3.medium': 0.068, 'db.m5.large': 0.171, 'db.r5.large': 0.24 },
      'oracle-se2': { 'db.t3.micro': 0.017, 'db.t3.small': 0.034, 'db.m5.large': 0.35 },
      'sqlserver-ex': { 'db.t3.micro': 0.018, 'db.t3.small': 0.036 },
    },
    storage: { 'gp2': 0.115, 'gp3': 0.115, 'io1': 0.125, 'magnetic': 0.10 },
    iops: 0.10,
  },
  
  // Aurora
  aurora: {
    instances: { 'db.r5.large': 0.29, 'db.r5.xlarge': 0.58, 'db.r6g.large': 0.26 },
    storage: 0.10,
    ioRequests: 0.20, // per million
    backtrackChanges: 0.012, // per million
  },
  
  // ElastiCache
  elasticache: {
    nodes: {
      'cache.t3.micro': 0.017, 'cache.t3.small': 0.034, 'cache.t3.medium': 0.068,
      'cache.m5.large': 0.155, 'cache.r5.large': 0.218,
    },
  },
  
  // DynamoDB
  dynamodb: {
    readCapacity: 0.00013,
    writeCapacity: 0.00065,
    onDemandRead: 0.25,
    onDemandWrite: 1.25,
    storage: 0.25,
    globalTables: 0.000975, // per replicated write
    streams: 0.02, // per 100k read requests
  },
  
  // Neptune
  neptune: {
    instances: { 'db.r5.large': 0.348, 'db.r5.xlarge': 0.696 },
    storage: 0.10,
    ioRequests: 0.20,
  },
  
  // DocumentDB
  documentdb: {
    instances: { 'db.r5.large': 0.277, 'db.r5.xlarge': 0.554 },
    storage: 0.10,
    ioRequests: 0.20,
  },
  
  // Redshift
  redshift: {
    instances: { 'dc2.large': 0.25, 'dc2.8xlarge': 4.80, 'ra3.xlplus': 1.086 },
  },
  
  // NAT Gateway
  natGateway: { hourly: 0.045, perGB: 0.045 },
  
  // Load Balancers
  loadBalancer: {
    alb: { hourly: 0.0225, lcuHourly: 0.008 },
    nlb: { hourly: 0.0225, lcuHourly: 0.006 },
    glb: { hourly: 0.0125, lcuHourly: 0.004 },
    clb: { hourly: 0.025 },
  },
  
  // VPC Endpoint
  vpcEndpoint: {
    interfaceHourly: 0.01,
    gatewayLoadBalancerHourly: 0.01,
    dataProcessed: 0.01,
  },
  
  // VPN
  vpnConnection: {
    hourly: 0.05,
    transitGatewayAttachment: 0.05,
    clientVpn: {
      endpointHourly: 0.05,
      connectionHourly: 0.05,
    },
  },
  
  // Transit Gateway
  transitGateway: {
    hourly: 0.05,
    dataProcessed: 0.02,
    peering: 0.05,
  },

  // Traffic Mirror
  trafficMirror: {
    sessionHourly: 0.15,
  },
  
  // Direct Connect
  directConnect: {
    portHours: { '1Gbps': 0.30, '10Gbps': 2.25 },
    dataTransfer: 0.02,
  },
  
  // Global Accelerator
  globalAccelerator: {
    hourly: 0.025,
    dataTransfer: 0.015,
  },
  
  // EKS
  eks: { clusterHourly: 0.10 },
  
  // ECS
  ecs: {
    fargateVcpuHourly: 0.04048,
    fargateMemoryGBHourly: 0.004445,
  },
  
  // ECR
  ecr: { storage: 0.10 },
  
  // Lambda
  lambda: {
    requests: 0.20,
    duration: 0.0000166667,
    provisionedConcurrency: 0.000004463,
  },
  
  // API Gateway
  apiGateway: {
    rest: 3.50,
    http: 1.00,
    websocket: 1.00,
    websocketMessages: 0.25,
  },
  
  // Step Functions
  stepFunctions: {
    standard: 25.00,
    express: 1.00,
  },
  
  // S3
  s3: {
    standardStorage: 0.023,
    standardIAStorage: 0.0125,
    oneZoneIAStorage: 0.01,
    glacierStorage: 0.004,
    glacierDeepArchive: 0.00099,
    intelligentTiering: 0.0025,
    requests: { put: 0.005, get: 0.0004, lifecycle: 0.01 },
  },
  
  // EFS
  efs: {
    standard: 0.30,
    ia: 0.016,
    provisionedThroughput: 6.00,
  },
  
  // FSx
  fsx: {
    lustre: 0.14,
    windows: 0.23,
    ontap: 0.25,
    openzfs: 0.09,
  },
  
  // Backup
  backup: {
    storage: 0.05,
    restoreStorage: 0.02,
  },
  
  // OpenSearch
  opensearch: {
    instances: {
      't3.small.search': 0.036, 't3.medium.search': 0.073,
      'm5.large.search': 0.142, 'r5.large.search': 0.186,
    },
    storage: 0.115,
    ultrawarmStorage: 0.024,
  },
  
  // Elasticsearch (legacy)
  elasticsearch: {
    instances: { 't3.small.elasticsearch': 0.036, 'm5.large.elasticsearch': 0.142 },
  },
  
  // Kinesis
  kinesis: {
    shardHourly: 0.015,
    payloadUnit: 0.014,
    extendedRetention: 0.02,
    enhancedFanout: 0.015,
  },
  
  // Kinesis Firehose
  kinesisFirehose: {
    dataIngested: 0.029,
    formatConversion: 0.018,
  },
  
  // Glue
  glue: {
    dpuHour: 0.44,
    crawlerDpuHour: 0.44,
    catalogStorage: 1.00,
    catalogRequests: 1.00,
  },
  
  // Athena
  athena: { dataScanned: 5.00 },
  
  // SQS
  sqs: { standard: 0.40, fifo: 0.50 },
  
  // SNS
  sns: {
    publish: 0.50,
    deliveries: { http: 0.60, email: 2.00, sms: 0.75, lambda: 0.00, sqs: 0.00 },
  },
  
  // EventBridge
  eventbridge: {
    customEvents: 1.00,
    partnerEvents: 1.00,
    archiveProcessed: 0.10,
    schemaDiscovery: 0.10,
  },
  
  // MQ
  mq: {
    instanceHourly: { 'mq.t3.micro': 0.027, 'mq.m5.large': 0.292 },
    storage: 0.10,
  },
  
  // MSK
  msk: {
    instanceHourly: { 'kafka.t3.small': 0.072, 'kafka.m5.large': 0.21 },
    storage: 0.10,
  },
  
  // Directory Service
  directoryService: {
    simpleAD: { small: 0.05, large: 0.15 },
    microsoftAD: { standard: 0.12, enterprise: 0.40 },
  },
  
  // MWAA
  mwaa: {
    environment: { 
      'mw1.small': 0.49, 
      'mw1.medium': 0.99, 
      'mw1.large': 1.99 
    },
  },
  
  // Kinesis Analytics
  kinesisAnalytics: {
    kpuHourly: 0.11,
    storage: 0.10,
  },

  // SSM
  ssm: {
    parameter: {
      standard: 0,
      advanced: 0.05,
      apiCalls: 0.05,
    },
    activation: {
      standard: 0,
      advanced: 0.00695,
    },
  },
  
  // Secrets Manager
  secretsManager: { secret: 0.40, apiCalls: 0.05 },
  
  // KMS
  kms: { key: 1.00, requests: 0.03 },
  
  // ACM
  acm: { privateCertificate: 0.75 },
  
  // WAF
  waf: { webACL: 5.00, rule: 1.00, requests: 0.60 },
  
  // GuardDuty
  guardDuty: { events: 4.00, s3Events: 0.80, eksEvents: 1.60 },
  
  // Macie
  macie: { bucketEvaluated: 0.10, dataScanned: 1.00 },
  
  // CloudWatch
  cloudwatch: {
    metrics: 0.30,
    alarmStandard: 0.10,
    alarmHighRes: 0.30,
    alarmAnomaly: 0.30,
    alarmComposite: 0.50,
    dashboards: 3.00,
    logsIngestion: 0.50,
    logsStorage: 0.03,
    logsInsightsQueries: 0.005,
    contributorInsightsRules: 0.50,
    contributorInsightsEvents: 0.02,
  },
  
  // CloudTrail
  cloudtrail: {
    managementEvents: 2.00,
    dataEvents: 0.10,
    insightsEvents: 0.35,
  },
  
  // Config
  config: {
    configItems: 0.003,
    rules: 1.00,
    conformancePackRules: 0.001,
  },
  
  // CodeBuild
  codebuild: {
    linuxSmall: 0.005,
    linuxMedium: 0.01,
    linuxLarge: 0.02,
    linux2xlarge: 0.04,
    armLarge: 0.015,
    gpuLarge: 0.18,
    windowsMedium: 0.02,
    windowsLarge: 0.04,
  },
  
  // CodePipeline
  codepipeline: {
    activePipeline: 1.00,
    trialPipelines: 0,
  },
  
  // CloudFront
  cloudfront: {
    dataTransfer: { 'us': 0.085, 'europe': 0.085, 'asia': 0.14, 'india': 0.17 },
    requests: { http: 0.0075, https: 0.01 },
    invalidations: 0.005,
    ssl: 600.00,
    originShield: 0.0090,
    realtimeLogs: 0.01,
    functions: 0.10,
  },
  
  // Route53
  route53: {
    hostedZone: 0.50,
    queries: 0.40,
    healthChecks: { basic: 0.50, https: 0.75, string: 1.00, fast: 1.00 },
    resolverEndpoint: 0.125,
    resolverQueries: 0.40,
  },
  
  // SageMaker
  sagemaker: {
    notebookInstances: { 'ml.t3.medium': 0.05, 'ml.m5.xlarge': 0.269 },
    trainingInstances: { 'ml.m5.xlarge': 0.269 },
    endpointInstances: { 'ml.m5.xlarge': 0.269 },
  },
  
  // Transfer Family
  transferFamily: {
    protocols: 0.30,
    dataProcessed: 0.04,
  },
  
  // DMS
  dms: {
    instances: { 'dms.t3.micro': 0.018, 'dms.r5.large': 0.206 },
  },
  
  // IoT
  iot: {
    connectivityMinutes: 0.08,
    messages: 1.00,
    ruleEngineActions: 0.15,
  },
  
  // Lightsail
  lightsail: {
    instances: { 'nano': 3.50, 'micro': 5.00, 'small': 10.00, 'medium': 20.00 },
  },
  
  // Beanstalk
  beanstalk: {},
  
  // Fargate (for backwards compatibility)
  fargate: {
    vcpuHourly: 0.04048,
    memoryGBHourly: 0.004445,
  },
  
  // Other (backwards compatibility)
  other: {
    dynamodb: { readCapacity: 0.00013, writeCapacity: 0.00065, onDemandRead: 0.25, onDemandWrite: 1.25, storage: 0.25 },
    s3: { standardStorage: 0.023, standardIAStorage: 0.0125, glacierStorage: 0.004 },
    apiGateway: { rest: 3.50, http: 1.00, websocket: 1.00 },
    sqs: { standard: 0.40, fifo: 0.50 },
    sns: { publish: 0.50 },
    cloudwatch: { metrics: 0.30, alarmStandard: 0.10, alarmHighRes: 0.30, dashboards: 3.00, logsIngestion: 0.50, logsStorage: 0.03 },
    secretsManager: { secret: 0.40, apiCalls: 0.05 },
    kms: { key: 1.00, requests: 0.03 },
    stepFunctions: { standard: 25.00, express: 1.00 },
    route53: { hostedZone: 0.50, queries: 0.40 },
    vpcEndpoint: { hourly: 0.01, dataProcessed: 0.01 },
    cognito: { mau: 0.0055 },
    eventBridge: { customEvents: 1.00 },
    kinesis: { shardHourly: 0.015, payloadUnit: 0.014 },
    efs: { standard: 0.30, ia: 0.016 },
    ecr: { storage: 0.10 },
    waf: { webACL: 5.00, rule: 1.00, requests: 0.60 },
    glue: { dpuHour: 0.44 },
    athena: { dataScanned: 5.00 },
  },
};

// Cache for loaded pricing data
let pricingDataCache: Record<string, AWSpricingData> | null = null;

/**
 * Load pricing data from JSON file
 */
function loadPricingData(): Record<string, AWSpricingData> {
  if (pricingDataCache) {
    return pricingDataCache;
  }
  
  // Try to load from data directory
  const dataPath = path.join(__dirname, '..', 'data', 'aws-pricing.json');
  
  try {
    if (fs.existsSync(dataPath)) {
      const data = JSON.parse(fs.readFileSync(dataPath, 'utf-8'));
      pricingDataCache = data;
      return data;
    }
  } catch (error) {
    console.warn('Warning: Could not load pricing data from file, using defaults');
  }
  
  // Return default pricing
  pricingDataCache = {
    'us-east-1': DEFAULT_PRICING,
    'ca-central-1': applyRegionalMultiplier(DEFAULT_PRICING, 1.05),
  };
  
  return pricingDataCache;
}

/**
 * Apply a multiplier to all prices in a pricing data object
 */
function applyRegionalMultiplier(pricing: AWSpricingData, multiplier: number): AWSpricingData {
  const result = JSON.parse(JSON.stringify(pricing)) as AWSpricingData;
  result.region = 'regional';
  
  // Helper to apply multiplier to nested objects
  const applyToRecord = (record: Record<string, number | Record<string, number>>) => {
    for (const key of Object.keys(record)) {
      if (typeof record[key] === 'number') {
        (record[key] as number) *= multiplier;
      } else if (typeof record[key] === 'object' && record[key] !== null) {
        applyToRecord(record[key] as Record<string, number>);
      }
    }
  };
  
  // Apply to all pricing sections
  applyToRecord(result.ec2.instances);
  applyToRecord(result.ebs.volumes);
  applyToRecord(result.ebs.iops);
  applyToRecord(result.ebs.throughput);
  result.ebs.snapshots *= multiplier;
  
  for (const engine of Object.keys(result.rds.instances)) {
    applyToRecord(result.rds.instances[engine]);
  }
  applyToRecord(result.rds.storage);
  result.rds.iops *= multiplier;
  
  applyToRecord(result.elasticache.nodes);
  
  result.dynamodb.readCapacity *= multiplier;
  result.dynamodb.writeCapacity *= multiplier;
  result.dynamodb.onDemandRead *= multiplier;
  result.dynamodb.onDemandWrite *= multiplier;
  result.dynamodb.storage *= multiplier;
  
  result.lambda.requests *= multiplier;
  result.lambda.duration *= multiplier;
  
  result.natGateway.hourly *= multiplier;
  result.natGateway.perGB *= multiplier;
  
  result.loadBalancer.alb.hourly *= multiplier;
  result.loadBalancer.alb.lcuHourly *= multiplier;
  result.loadBalancer.nlb.hourly *= multiplier;
  result.loadBalancer.nlb.lcuHourly *= multiplier;
  result.loadBalancer.clb.hourly *= multiplier;
  
  result.eks.clusterHourly *= multiplier;
  result.ecs.fargateVcpuHourly *= multiplier;
  result.ecs.fargateMemoryGBHourly *= multiplier;
  result.fargate.vcpuHourly *= multiplier;
  result.fargate.memoryGBHourly *= multiplier;
  
  applyToRecord(result.opensearch.instances);
  applyToRecord(result.documentdb.instances);

  result.directoryService.simpleAD.small *= multiplier;
  result.directoryService.simpleAD.large *= multiplier;
  result.directoryService.microsoftAD.standard *= multiplier;
  result.directoryService.microsoftAD.enterprise *= multiplier;
  
  applyToRecord(result.mwaa.environment);
  
  result.kinesisAnalytics.kpuHourly *= multiplier;
  result.kinesisAnalytics.storage *= multiplier;
  
  return result;
}

/**
 * Get pricing data for a specific region
 */
export function getRegionalPricing(region: string): AWSpricingData {
  const allPricing = loadPricingData();
  
  // Return exact match if available
  if (allPricing[region]) {
    return allPricing[region];
  }
  
  // Fall back to us-east-1 with regional multiplier
  const basePricing = allPricing['us-east-1'] || DEFAULT_PRICING;
  const multiplier = REGIONAL_MULTIPLIERS[region] || 1.1;
  
  return applyRegionalMultiplier(basePricing, multiplier);
}

// Regional pricing multipliers (relative to us-east-1)
const REGIONAL_MULTIPLIERS: Record<string, number> = {
  'us-east-1': 1.0,
  'us-east-2': 1.0,
  'us-west-1': 1.1,
  'us-west-2': 1.0,
  'ca-central-1': 1.05,
  'eu-west-1': 1.05,
  'eu-west-2': 1.08,
  'eu-west-3': 1.1,
  'eu-central-1': 1.08,
  'eu-north-1': 1.05,
  'eu-south-1': 1.1,
  'ap-southeast-1': 1.1,
  'ap-southeast-2': 1.15,
  'ap-southeast-3': 1.12,
  'ap-northeast-1': 1.15,
  'ap-northeast-2': 1.12,
  'ap-northeast-3': 1.15,
  'ap-south-1': 1.05,
  'ap-east-1': 1.15,
  'sa-east-1': 1.5,
  'af-south-1': 1.3,
  'me-south-1': 1.2,
  'me-central-1': 1.2,
  // GovCloud
  'us-gov-west-1': 1.2,
  'us-gov-east-1': 1.2,
  // China
  'cn-north-1': 1.1,
  'cn-northwest-1': 1.1,
};

/**
 * Resource types that are always free or have no direct cost
 * Reference: https://www.infracost.io/docs/supported_resources/aws/ (Free resources section)
 * 
 * This is the EXACT list from Infracost docs, converted to CloudFormation resource types.
 * Terraform aws_* -> CloudFormation AWS::*
 */
export const FREE_RESOURCES = new Set([
  // Access Analyzer
  'AWS::AccessAnalyzer::Analyzer',
  'AWS::AccessAnalyzer::ArchiveRule',
  
  // ACM
  'AWS::CertificateManager::Certificate', // aws_acm_certificate_validation equivalent
  
  // ACM PCA
  'AWS::ACMPCA::Permission',
  'AWS::ACMPCA::Policy',
  
  // Account
  'AWS::Account::AlternateContact',
  
  // ALB/ELB (listeners, target groups, attachments)
  'AWS::ElasticLoadBalancingV2::ListenerCertificate',
  'AWS::ElasticLoadBalancingV2::ListenerRule',
  'AWS::ElasticLoadBalancingV2::Listener',
  'AWS::ElasticLoadBalancingV2::TargetGroup',
  
  // AMI
  'AWS::EC2::AMI', // aws_ami_launch_permission equivalent
  
  // Amplify
  'AWS::Amplify::App', // aws_amplify_backend_environment equivalent
  'AWS::Amplify::Branch',
  'AWS::Amplify::Domain',
  
  // API Gateway
  'AWS::ApiGateway::Account',
  'AWS::ApiGateway::ApiKey',
  'AWS::ApiGateway::Authorizer',
  'AWS::ApiGateway::BasePathMapping',
  'AWS::ApiGateway::ClientCertificate',
  'AWS::ApiGateway::Deployment',
  'AWS::ApiGateway::DocumentationPart',
  'AWS::ApiGateway::DocumentationVersion',
  'AWS::ApiGateway::DomainName',
  'AWS::ApiGateway::GatewayResponse',
  'AWS::ApiGateway::Integration', // aws_api_gateway_integration
  'AWS::ApiGateway::IntegrationResponse', // aws_api_gateway_integration_response
  'AWS::ApiGateway::Method',
  'AWS::ApiGateway::MethodResponse',
  'AWS::ApiGateway::Model',
  'AWS::ApiGateway::RequestValidator',
  'AWS::ApiGateway::Resource',
  'AWS::ApiGateway::RestApiPolicy',
  'AWS::ApiGateway::UsagePlan',
  'AWS::ApiGateway::UsagePlanKey',
  'AWS::ApiGateway::VpcLink',
  
  // API Gateway V2
  'AWS::ApiGatewayV2::ApiMapping',
  'AWS::ApiGatewayV2::Authorizer',
  'AWS::ApiGatewayV2::Deployment',
  'AWS::ApiGatewayV2::DomainName',
  'AWS::ApiGatewayV2::Integration',
  'AWS::ApiGatewayV2::IntegrationResponse',
  'AWS::ApiGatewayV2::Model',
  'AWS::ApiGatewayV2::Route',
  'AWS::ApiGatewayV2::RouteResponse',
  'AWS::ApiGatewayV2::Stage',
  'AWS::ApiGatewayV2::VpcLink',
  
  // Application Auto Scaling
  'AWS::ApplicationAutoScaling::ScalingPolicy',
  'AWS::ApplicationAutoScaling::ScheduledAction',
  
  // AppConfig
  'AWS::AppConfig::Extension',
  'AWS::AppConfig::ExtensionAssociation',
  'AWS::AppConfig::HostedConfigurationVersion',
  
  // AppFlow
  'AWS::AppFlow::ConnectorProfile',
  
  // AppIntegrations
  'AWS::AppIntegrations::EventIntegration',
  
  // App Mesh
  'AWS::AppMesh::GatewayRoute',
  'AWS::AppMesh::Mesh',
  'AWS::AppMesh::Route',
  'AWS::AppMesh::VirtualGateway',
  'AWS::AppMesh::VirtualNode',
  'AWS::AppMesh::VirtualRouter',
  'AWS::AppMesh::VirtualService',
  
  // Auto Scaling
  'AWS::AutoScaling::LifecycleHook',
  'AWS::AutoScaling::NotificationConfiguration',
  'AWS::AutoScaling::ScalingPolicy',
  'AWS::EC2::PlacementGroup',
  
  // Backup
  'AWS::Backup::BackupPlan',
  'AWS::Backup::BackupSelection',
  'AWS::Backup::GlobalSettings',
  'AWS::Backup::RegionSettings',
  'AWS::Backup::BackupVaultNotifications',
  'AWS::Backup::BackupVaultPolicy',
  
  // CloudFormation
  'AWS::CloudFormation::StackSet', // aws_cloudformation_stack_set_instance equivalent
  'AWS::CloudFormation::ResourceVersion', // aws_cloudformation_type equivalent
  
  // CloudFront
  'AWS::CloudFront::OriginAccessIdentity', // aws_cloudfront_origin_access_identity
  'AWS::CloudFront::PublicKey',
  
  // CloudWatch Events
  'AWS::Events::Rule',
  'AWS::Events::EventBus',
  
  // CloudWatch Logs (aws_cloudwatch_log_group is PAID - has data ingestion costs!)
  // These are free configuration resources:
  'AWS::Logs::Destination',
  'AWS::Logs::DestinationPolicy',
  'AWS::Logs::MetricFilter',
  'AWS::Logs::ResourcePolicy',
  'AWS::Logs::LogStream',
  'AWS::Logs::SubscriptionFilter',
  
  // CodeBuild
  'AWS::CodeBuild::ReportGroup',
  'AWS::CodeBuild::SourceCredential',
  
  // Config
  'AWS::Config::AggregationAuthorization',
  'AWS::Config::ConfigurationAggregator',
  'AWS::Config::ConfigurationRecorderStatus', // aws_config_configuration_recorder_status
  'AWS::Config::DeliveryChannel',
  'AWS::Config::RemediationConfiguration',
  
  // Customer Gateway
  'AWS::EC2::CustomerGateway',
  
  // RDS/DB
  'AWS::RDS::DBInstanceRoleAssociation', // aws_db_instance_role_association
  'AWS::RDS::OptionGroup',
  'AWS::RDS::DBParameterGroup',
  'AWS::RDS::DBSubnetGroup',
  
  // Default VPC resources
  'AWS::EC2::NetworkAcl', // aws_default_network_acl
  'AWS::EC2::RouteTable', // aws_default_route_table
  'AWS::EC2::SecurityGroup', // aws_default_security_group
  'AWS::EC2::Subnet', // aws_default_subnet
  'AWS::EC2::DHCPOptions', // aws_default_vpc_dhcp_options
  'AWS::EC2::VPC', // aws_default_vpc
  
  // DMS
  'AWS::DMS::ReplicationSubnetGroup',
  'AWS::DMS::ReplicationTask',
  
  // DocumentDB
  'AWS::DocDB::DBClusterParameterGroup',
  'AWS::DocDB::DBSubnetGroup',
  
  // Direct Connect
  'AWS::DirectConnect::BGPPeer', // aws_dx_bgp_peer
  'AWS::DirectConnect::GatewayAssociationProposal', // aws_dx_gateway_association_proposal
  'AWS::DirectConnect::DirectConnectGateway', // aws_dx_gateway
  'AWS::DirectConnect::HostedPrivateVirtualInterfaceAccepter',
  'AWS::DirectConnect::HostedPrivateVirtualInterface',
  'AWS::DirectConnect::HostedPublicVirtualInterfaceAccepter',
  'AWS::DirectConnect::HostedPublicVirtualInterface',
  'AWS::DirectConnect::HostedTransitVirtualInterfaceAccepter',
  'AWS::DirectConnect::HostedTransitVirtualInterface',
  'AWS::DirectConnect::Lag',
  'AWS::DirectConnect::PrivateVirtualInterface',
  'AWS::DirectConnect::PublicVirtualInterface',
  'AWS::DirectConnect::TransitVirtualInterface',
  
  // DynamoDB
  'AWS::DynamoDB::TableItem', // aws_dynamodb_table_item - not a real CFN type but good to have
  
  // EBS
  'AWS::EC2::EncryptionByDefault', // aws_ebs_encryption_by_default
  
  // EC2 Client VPN
  'AWS::EC2::ClientVpnAuthorizationRule',
  'AWS::EC2::ClientVpnRoute',
  
  // EC2 Tags
  'AWS::EC2::Tag', // aws_ec2_tag - not a standard CFN type
  
  // EC2 Traffic Mirror
  'AWS::EC2::TrafficMirrorFilterRule',
  'AWS::EC2::TrafficMirrorFilter',
  'AWS::EC2::TrafficMirrorTarget',
  
  // EC2 Transit Gateway
  'AWS::EC2::TransitGateway', // Free per Infracost
  'AWS::EC2::TransitGatewayPeeringAttachmentAccepter',
  'AWS::EC2::TransitGatewayRouteTable',
  'AWS::EC2::TransitGatewayRouteTableAssociation',
  'AWS::EC2::TransitGatewayRouteTablePropagation',
  'AWS::EC2::TransitGatewayRoute',
  'AWS::EC2::TransitGatewayVpcAttachmentAccepter',
  
  // ECR
  'AWS::ECR::LifecyclePolicy',
  'AWS::ECR::RepositoryPolicy',
  
  // ECS
  'AWS::ECS::AccountSettingDefault',
  'AWS::ECS::CapacityProvider',
  'AWS::ECS::Cluster',
  'AWS::ECS::TaskDefinition',
  
  // Egress Only Internet Gateway
  'AWS::EC2::EgressOnlyInternetGateway',
  
  // EFS
  'AWS::EFS::AccessPoint',
  'AWS::EFS::FileSystemPolicy',
  'AWS::EFS::MountTarget',
  
  // EIP
  'AWS::EC2::EIPAssociation',
  
  // EKS
  'AWS::EKS::Addon',
  'AWS::EKS::IdentityProviderConfig',
  
  // ElastiCache
  'AWS::ElastiCache::ParameterGroup',
  'AWS::ElastiCache::SecurityGroup',
  'AWS::ElastiCache::SubnetGroup',
  'AWS::ElastiCache::User',
  'AWS::ElastiCache::UserGroup',
  'AWS::ElastiCache::UserGroupAssociation',
  
  // Elasticsearch
  'AWS::Elasticsearch::DomainPolicy',
  
  // Elastic Beanstalk
  'AWS::ElasticBeanstalk::Application',
  
  // ELB
  'AWS::ElasticLoadBalancing::LoadBalancerAttachment', // aws_elb_attachment
  
  // Flow Logs
  'AWS::EC2::FlowLog',
  
  // Glue
  'AWS::Glue::Table',
  'AWS::Glue::Classifier',
  'AWS::Glue::Connection',
  'AWS::Glue::DataCatalogEncryptionSettings',
  'AWS::Glue::Partition',
  'AWS::Glue::PartitionIndex',
  'AWS::Glue::Registry',
  'AWS::Glue::ResourcePolicy',
  'AWS::Glue::Schema',
  'AWS::Glue::SecurityConfiguration',
  'AWS::Glue::Trigger',
  'AWS::Glue::UserDefinedFunction',
  'AWS::Glue::Workflow',
  
  // IAM
  'AWS::IAM::AccessKey',
  'AWS::IAM::AccountAlias',
  'AWS::IAM::AccountPasswordPolicy',
  'AWS::IAM::Group',
  'AWS::IAM::GroupPolicy',
  'AWS::IAM::InstanceProfile',
  'AWS::IAM::ManagedPolicy',
  'AWS::IAM::OIDCProvider',
  'AWS::IAM::Policy',
  'AWS::IAM::Role',
  'AWS::IAM::RolePolicy',
  'AWS::IAM::SAMLProvider',
  'AWS::IAM::ServerCertificate',
  'AWS::IAM::ServiceLinkedRole',
  'AWS::IAM::User',
  'AWS::IAM::UserPolicy',
  'AWS::IAM::UserToGroupAddition',
  
  // Internet Gateway
  'AWS::EC2::InternetGateway',
  
  // IoT
  'AWS::IoT::Policy',
  
  // Key Pair
  'AWS::EC2::KeyPair',
  
  // KMS
  'AWS::KMS::Alias',
  'AWS::KMS::Ciphertext',
  'AWS::KMS::Grant',
  
  // Lambda
  'AWS::Lambda::Alias',
  'AWS::Lambda::CodeSigningConfig',
  'AWS::Lambda::EventSourceMapping',
  'AWS::Lambda::EventInvokeConfig',
  'AWS::Lambda::LayerVersion',
  'AWS::Lambda::LayerVersionPermission',
  'AWS::Lambda::Permission',
  
  // Launch Configuration/Template
  'AWS::AutoScaling::LaunchConfiguration',
  'AWS::EC2::LaunchTemplate',
  
  // LB (same as ALB)
  'AWS::ElasticLoadBalancing::LoadBalancerCookieStickinessPolicy',
  
  // Lightsail
  'AWS::Lightsail::Domain',
  'AWS::Lightsail::KeyPair',
  'AWS::Lightsail::StaticIp',
  'AWS::Lightsail::StaticIpAttachment',
  
  // Load Balancer Policies
  'AWS::ElasticLoadBalancing::LoadBalancerPolicy',
  
  // Main Route Table
  'AWS::EC2::MainRouteTableAssociation',
  
  // MQ
  'AWS::AmazonMQ::Configuration',
  
  // MSK
  'AWS::MSK::Configuration',
  
  // Neptune
  'AWS::Neptune::DBClusterParameterGroup',
  'AWS::Neptune::EventSubscription',
  'AWS::Neptune::DBParameterGroup',
  'AWS::Neptune::DBSubnetGroup',
  
  // Network ACL
  'AWS::EC2::NetworkAclEntry',
  
  // Network Interface
  'AWS::EC2::NetworkInterfaceAttachment',
  'AWS::EC2::NetworkInterface',
  
  // Network Firewall
  'AWS::NetworkFirewall::RuleGroup',
  'AWS::NetworkFirewall::FirewallPolicy',
  'AWS::NetworkFirewall::LoggingConfiguration',
  
  // RAM
  'AWS::RAM::PrincipalAssociation',
  'AWS::RAM::ResourceAssociation',
  'AWS::RAM::ResourceShareAccepter',
  'AWS::RAM::ResourceShare',
  
  // RDS Cluster
  'AWS::RDS::DBClusterEndpoint',
  'AWS::RDS::DBClusterParameterGroup',
  
  // Resource Groups
  'AWS::ResourceGroups::Group',
  
  // Route 53 Resolver
  'AWS::Route53Resolver::DNSSECConfig',
  'AWS::Route53Resolver::QueryLoggingConfigAssociation',
  'AWS::Route53Resolver::QueryLoggingConfig',
  'AWS::Route53Resolver::ResolverRuleAssociation',
  'AWS::Route53Resolver::ResolverRule',
  
  // Route 53 Zone Association
  'AWS::Route53::HostedZoneVPCAssociation',
  
  // Route Table
  'AWS::EC2::SubnetRouteTableAssociation',
  'AWS::EC2::Route',
  
  // S3
  'AWS::S3::AccessPoint',
  'AWS::S3::AccountPublicAccessBlock',
  'AWS::S3::BucketPolicy',
  
  // Secrets Manager
  'AWS::SecretsManager::SecretPolicy',
  'AWS::SecretsManager::RotationSchedule',
  'AWS::SecretsManager::SecretTargetAttachment', // aws_secretsmanager_secret_version equivalent
  
  // Security Group
  'AWS::EC2::SecurityGroupIngress',
  'AWS::EC2::SecurityGroupEgress',
  
  // Service Discovery
  'AWS::ServiceDiscovery::Service',
  
  // SES
  'AWS::SES::DomainDKIM',
  'AWS::SES::DomainIdentity',
  
  // SNS
  'AWS::SNS::PlatformApplication',
  'AWS::SNS::TopicPolicy',
  
  // SQS
  'AWS::SQS::QueuePolicy',
  
  // SSM (NOT aws_ssm_parameter - that has costs!)
  'AWS::SSM::Association',
  'AWS::SSM::MaintenanceWindow',
  'AWS::SSM::MaintenanceWindowTarget',
  'AWS::SSM::MaintenanceWindowTask',
  'AWS::SSM::PatchBaseline',
  'AWS::SSM::PatchGroup',
  'AWS::SSM::ResourceDataSync',
  
  // Subnet
  // Already covered by AWS::EC2::Subnet
  
  // Transfer Family
  'AWS::Transfer::Access',
  'AWS::Transfer::SshKey',
  'AWS::Transfer::User',
  
  // Volume Attachment
  'AWS::EC2::VolumeAttachment',
  
  // VPC
  'AWS::EC2::VPCDHCPOptionsAssociation',
  'AWS::EC2::VPCEndpointConnectionNotification',
  'AWS::EC2::VPCEndpointRouteTableAssociation',
  'AWS::EC2::VPCEndpointServiceAllowedPrincipal',
  'AWS::EC2::VPCEndpointService',
  'AWS::EC2::VPCEndpointSubnetAssociation',
  'AWS::EC2::VPCCidrBlock',
  'AWS::EC2::VPCPeeringConnectionAccepter',
  'AWS::EC2::VPCPeeringConnectionOptions',
  'AWS::EC2::VPCPeeringConnection',
  
  // VPN
  'AWS::EC2::VPNConnectionRoute',
  'AWS::EC2::VPNGatewayAttachment',
  'AWS::EC2::VPNGatewayRoutePropagation',
  'AWS::EC2::VPNGateway',
  
  // WAF (classic)
  'AWS::WAF::ByteMatchSet',
  'AWS::WAF::GeoMatchSet',
  'AWS::WAF::IPSet',
  'AWS::WAF::RateBasedRule',
  'AWS::WAF::RegexMatchSet',
  'AWS::WAF::RegexPatternSet',
  'AWS::WAF::RuleGroup',
  'AWS::WAF::Rule',
  'AWS::WAF::SizeConstraintSet',
  'AWS::WAF::SqlInjectionMatchSet',
  'AWS::WAF::XssMatchSet',
  
  // WAFv2
  'AWS::WAFv2::IPSet',
  'AWS::WAFv2::RegexPatternSet',
  'AWS::WAFv2::RuleGroup',
  'AWS::WAFv2::WebACLAssociation',
  'AWS::WAFv2::LoggingConfiguration',
  
  // CDK Metadata (not in Infracost but useful)
  'AWS::CDK::Metadata',
  
  // Custom resources
  'Custom::*',
]);

// Resources that have costs but are difficult to estimate without usage data
export const USAGE_BASED_RESOURCES = new Set([
  'AWS::Lambda::Function',
  'AWS::DynamoDB::Table',
  'AWS::S3::Bucket',
  'AWS::SNS::Topic', // Publishing has costs
  'AWS::SQS::Queue',
  'AWS::ApiGateway::RestApi',
  'AWS::ApiGatewayV2::Api',
  'AWS::StepFunctions::StateMachine',
  'AWS::Kinesis::Stream',
  'AWS::Firehose::DeliveryStream',
  'AWS::CloudFront::Distribution',
  'AWS::Logs::LogGroup', // Data ingestion and storage costs
  'AWS::Glue::Job',
  'AWS::Glue::Crawler',
  'AWS::Athena::WorkGroup',
  'AWS::CodeBuild::Project',
  'AWS::ECR::Repository',
  'AWS::EFS::FileSystem',
  'AWS::WAFv2::WebACL',
  'AWS::WAF::WebACL',
  'AWS::SSM::Parameter', // Has costs for parameter storage and API calls
  'AWS::Route53::RecordSet',
]);

/**
 * Get the last update time of pricing data
 */
export function getPricingDataLastUpdated(): string | null {
  const allPricing = loadPricingData();
  const usEast = allPricing['us-east-1'];
  return usEast?.lastUpdated || null;
}

/**
 * Check if pricing data needs to be updated (older than 7 days)
 */
export function isPricingDataStale(): boolean {
  const lastUpdated = getPricingDataLastUpdated();
  if (!lastUpdated) return true;
  
  const updateDate = new Date(lastUpdated);
  const now = new Date();
  const daysSinceUpdate = (now.getTime() - updateDate.getTime()) / (1000 * 60 * 60 * 24);
  
  return daysSinceUpdate > 7;
}
