/**
 * AWS Pricing Data Module
 * Loads pricing data from JSON file generated by Infracost API
 * 
 * Supported resources reference: https://www.infracost.io/docs/supported_resources/aws/
 */

import * as fs from 'fs';
import * as path from 'path';

export const HOURS_PER_MONTH = 730;
export const DEFAULT_REGION = 'us-east-1';

// Pricing data structure from JSON file - comprehensive coverage of Infracost-supported resources
export interface AWSpricingData {
  region: string;
  lastUpdated: string;
  
  // Compute
  ec2: {
    instances: Record<string, number>;
    hosts: Record<string, number>;
  };
  ebs: {
    volumes: Record<string, number>;
    iops: Record<string, number>;
    throughput: Record<string, number>;
    snapshots: number;
  };
  
  // Database
  rds: {
    instances: Record<string, Record<string, number>>;
    storage: Record<string, number>;
    iops: number;
  };
  aurora: {
    instances: Record<string, number>;
    storage: number;
    ioRequests: number;
    backtrackChanges: number;
  };
  elasticache: {
    nodes: Record<string, number>;
  };
  dynamodb: {
    readCapacity: number;
    writeCapacity: number;
    onDemandRead: number;
    onDemandWrite: number;
    storage: number;
    globalTables: number;
    streams: number;
  };
  neptune: {
    instances: Record<string, number>;
    storage: number;
    ioRequests: number;
  };
  documentdb: {
    instances: Record<string, number>;
    storage: number;
    ioRequests: number;
  };
  redshift: {
    instances: Record<string, number>;
  };
  
  // Networking
  natGateway: {
    hourly: number;
    perGB: number;
  };
  loadBalancer: {
    alb: { hourly: number; lcuHourly: number };
    nlb: { hourly: number; lcuHourly: number };
    glb: { hourly: number; lcuHourly: number };
    clb: { hourly: number };
  };
  vpcEndpoint: {
    interfaceHourly: number;
    gatewayLoadBalancerHourly: number;
    dataProcessed: number;
  };
  vpnConnection: {
    hourly: number;
    transitGatewayAttachment: number;
    clientVpn: {
      endpointHourly: number;
      connectionHourly: number;
    };
  };
  transitGateway: {
    hourly: number;
    dataProcessed: number;
    peering: number;
  };
  trafficMirror: {
    sessionHourly: number;
  };
  directConnect: {
    portHours: Record<string, number>;
    dataTransfer: number;
  };
  globalAccelerator: {
    hourly: number;
    dataTransfer: number;
  };
  
  // Containers & Orchestration
  eks: {
    clusterHourly: number;
    fargateVcpuHourly?: number;
    fargateMemoryGBHourly?: number;
  };
  ecs: {
    fargateVcpuHourly: number;
    fargateMemoryGBHourly: number;
  };
  ecr: {
    storage: number;
  };
  
  // Serverless
  lambda: {
    requests: number;
    duration: number;
    durationArm?: number;
    provisionedConcurrency: number;
  };
  apiGateway: {
    rest: number;
    http: number;
    websocket: number;
    websocketMessages: number;
  };
  stepFunctions: {
    standard: number;
    express: number;
  };
  
  // Storage
  s3: {
    standardStorage: number;
    standardIAStorage: number;
    oneZoneIAStorage: number;
    glacierStorage: number;
    glacierDeepArchive: number;
    intelligentTiering: number;
    requests: {
      put: number;
      get: number;
      lifecycle: number;
    };
  };
  efs: {
    standard: number;
    ia: number;
    provisionedThroughput: number;
  };
  fsx: {
    lustre: number;
    windows: number;
    ontap: number;
    openzfs: number;
  };
  backup: {
    storage: number;
    restoreStorage: number;
  };
  
  // Search & Analytics
  opensearch: {
    instances: Record<string, number>;
    storage: number;
    ultrawarmStorage: number;
  };
  elasticsearch: {
    instances: Record<string, number>;
  };
  kinesis: {
    shardHourly: number;
    payloadUnit: number;
    extendedRetention: number;
    enhancedFanout: number;
  };
  kinesisFirehose: {
    dataIngested: number;
    formatConversion: number;
  };
  glue: {
    dpuHour: number;
    crawlerDpuHour: number;
    catalogStorage: number;
    catalogRequests: number;
  };
  athena: {
    dataScanned: number;
  };
  
  // Messaging
  sqs: {
    standard: number;
    fifo: number;
  };
  sns: {
    publish: number;
    deliveries: {
      http: number;
      email: number;
      sms: number;
      lambda: number;
      sqs: number;
    };
  };
  eventbridge: {
    customEvents: number;
    partnerEvents: number;
    archiveProcessed: number;
    schemaDiscovery: number;
  };
  mq: {
    instanceHourly: Record<string, number>;
    storage: number;
  };
  msk: {
    instanceHourly: Record<string, number>;
    storage: number;
  };
  
  // Directory Service
  directoryService: {
    simpleAD: {
      small: number;
      large: number;
    };
    microsoftAD: {
      standard: number;
      enterprise: number;
    };
  };
  
  // MWAA
  mwaa: {
    environment: Record<string, number>; // mw1.small, medium, large
  };
  
  // Kinesis Analytics
  kinesisAnalytics: {
    kpuHourly: number;
    storage: number;
  };
  
  // Security & Identity
  ssm: {
    parameter: {
      standard: number;
      advanced: number;
      apiCalls: number;
    };
    activation: {
      standard: number;
      advanced: number;
    };
  };
  secretsManager: {
    secret: number;
    apiCalls: number;
  };
  kms: {
    key: number;
    requests: number;
  };
  acm: {
    privateCertificate: number;
  };
  waf: {
    webACL: number;
    rule: number;
    requests: number;
  };
  guardDuty: {
    events: number;
    s3Events: number;
    eksEvents: number;
  };
  macie: {
    bucketEvaluated: number;
    dataScanned: number;
  };
  
  // Management & Monitoring
  cloudwatch: {
    metrics: number;
    alarmStandard: number;
    alarmHighRes: number;
    alarmAnomaly: number;
    alarmComposite: number;
    dashboards: number;
    logsIngestion: number;
    logsStorage: number;
    logsInsightsQueries: number;
    contributorInsightsRules: number;
    contributorInsightsEvents: number;
  };
  cloudtrail: {
    managementEvents: number;
    dataEvents: number;
    insightsEvents: number;
  };
  config: {
    configItems: number;
    rules: number;
    conformancePackRules: number;
  };
  
  // Developer Tools
  codebuild: {
    linuxSmall: number;
    linuxMedium: number;
    linuxLarge: number;
    linux2xlarge: number;
    armLarge: number;
    gpuLarge: number;
    windowsMedium: number;
    windowsLarge: number;
  };
  codepipeline: {
    activePipeline: number;
    trialPipelines: number;
  };
  
  // Content Delivery
  cloudfront: {
    dataTransfer: Record<string, number>;
    requests: {
      http: number;
      https: number;
    };
    invalidations: number;
    ssl: number;
    originShield: number;
    realtimeLogs: number;
    functions: number;
  };
  
  // DNS
  route53: {
    hostedZone: number;
    queries: number;
    healthChecks: {
      basic: number;
      https: number;
      string: number;
      fast: number;
    };
    resolverEndpoint: number;
    resolverQueries: number;
  };
  
  // Machine Learning
  sagemaker: {
    notebookInstances: Record<string, number>;
    trainingInstances: Record<string, number>;
    endpointInstances: Record<string, number>;
  };
  
  // Transfer & Migration
  transferFamily: {
    protocols: number;
    dataProcessed: number;
  };
  dms: {
    instances: Record<string, number>;
  };
  
  // IoT
  iot: {
    connectivityMinutes: number;
    messages: number;
    ruleEngineActions: number;
  };
  
  // Other services
  lightsail: {
    instances: Record<string, number>;
  };
  beanstalk: {
    // Environment cost is based on underlying resources
  };
  
  // Backwards compatibility
  fargate: {
    vcpuHourly: number;
    memoryGBHourly: number;
  };
  
  // Generic other pricing
  other: {
    // Keeping for backwards compatibility - these are now in specific sections above
    dynamodb?: {
      readCapacity: number;
      writeCapacity: number;
      onDemandRead: number;
      onDemandWrite: number;
      storage: number;
    };
    s3?: {
      standardStorage: number;
      standardIAStorage: number;
      glacierStorage: number;
    };
    apiGateway?: {
      rest: number;
      http: number;
      websocket: number;
    };
    sqs?: {
      standard: number;
      fifo: number;
    };
    sns?: {
      publish: number;
    };
    cloudwatch?: {
      metrics: number;
      alarmStandard: number;
      alarmHighRes: number;
      dashboards: number;
      logsIngestion: number;
      logsStorage: number;
    };
    secretsManager?: {
      secret: number;
      apiCalls: number;
    };
    kms?: {
      key: number;
      requests: number;
    };
    stepFunctions?: {
      standard: number;
      express: number;
    };
    route53?: {
      hostedZone: number;
      queries: number;
    };
    vpcEndpoint?: {
      hourly: number;
      dataProcessed: number;
    };
    cognito?: {
      mau: number;
    };
    eventBridge?: {
      customEvents: number;
    };
    kinesis?: {
      shardHourly: number;
      payloadUnit: number;
    };
    efs?: {
      standard: number;
      ia: number;
    };
    ecr?: {
      storage: number;
    };
    waf?: {
      webACL: number;
      rule: number;
      requests: number;
    };
    glue?: {
      dpuHour: number;
    };
    athena?: {
      dataScanned: number;
    };
  };
}
// Cache for loaded pricing data
let pricingDataCache: Record<string, AWSpricingData> | null = null;

/**
 * Load pricing data from JSON file
 */
function loadPricingData(): Record<string, AWSpricingData> {
  if (pricingDataCache) {
    return pricingDataCache;
  }
  
  // Try to load from data directory (multiple possible locations)
  const possiblePaths = [
    // 1. In dist/data/ (bundled) - path.join(__dirname, 'data', 'aws-pricing.json')
    // When in dist/pricing-data.js, __dirname is dist.
    path.join(__dirname, 'data', 'aws-pricing.json'),
    
    // 2. In ../data/ (dev/source) - path.join(__dirname, '..', 'data', 'aws-pricing.json')
    // When in src/pricing-data.ts, __dirname is src.
    path.join(__dirname, '..', 'data', 'aws-pricing.json')
  ];

  for (const dataPath of possiblePaths) {
    try {
      if (fs.existsSync(dataPath)) {
        const data = JSON.parse(fs.readFileSync(dataPath, 'utf-8'));
        pricingDataCache = data;
        return data;
      }
    } catch (error) {
      // Continue to next path
    }
  }
  
  console.warn('Warning: Could not load pricing data from file. Please run "npm run update-pricing" to fetch data.');
  
  // If we can't load data, we can't provide meaningful estimates
  // Returning empty object which will likely cause lookups to fail gracefully or return undefined/NaN costs
  // rather than hardcoded potentially wrong values.
  pricingDataCache = {};
  return pricingDataCache;
}

/**
 * Get pricing data for a specific region
 */
export function getRegionalPricing(region: string): AWSpricingData {
  const allPricing = loadPricingData();
  
  // Return exact match if available
  if (allPricing[region]) {
    return allPricing[region];
  }
  
  // If no base pricing (e.g. no file loaded), we can't provide data
  // But we must return an object matching the interface to avoid runtime crashes
  // It will be empty/undefined values mostly
  return {} as AWSpricingData;
}

/**
 * Resource types that are always free or have no direct cost
 * Reference: https://www.infracost.io/docs/supported_resources/aws/ (Free resources section)
 * 
 * This is the EXACT list from Infracost docs, converted to CloudFormation resource types.
 * Terraform aws_* -> CloudFormation AWS::*
 */
export const FREE_RESOURCES = new Set([
  // Access Analyzer
  'AWS::AccessAnalyzer::Analyzer',
  'AWS::AccessAnalyzer::ArchiveRule',
  
  // ACM
  'AWS::CertificateManager::Certificate', // aws_acm_certificate_validation equivalent
  
  // ACM PCA
  'AWS::ACMPCA::Permission',
  'AWS::ACMPCA::Policy',
  
  // Account
  'AWS::Account::AlternateContact',
  
  // ALB/ELB (listeners, target groups, attachments)
  'AWS::ElasticLoadBalancingV2::ListenerCertificate',
  'AWS::ElasticLoadBalancingV2::ListenerRule',
  'AWS::ElasticLoadBalancingV2::Listener',
  'AWS::ElasticLoadBalancingV2::TargetGroup',
  
  // AMI
  'AWS::EC2::AMI', // aws_ami_launch_permission equivalent
  
  // Amplify
  'AWS::Amplify::App', // aws_amplify_backend_environment equivalent
  'AWS::Amplify::Branch',
  'AWS::Amplify::Domain',
  
  // API Gateway
  'AWS::ApiGateway::Account',
  'AWS::ApiGateway::ApiKey',
  'AWS::ApiGateway::Authorizer',
  'AWS::ApiGateway::BasePathMapping',
  'AWS::ApiGateway::ClientCertificate',
  'AWS::ApiGateway::Deployment',
  'AWS::ApiGateway::DocumentationPart',
  'AWS::ApiGateway::DocumentationVersion',
  'AWS::ApiGateway::DomainName',
  'AWS::ApiGateway::GatewayResponse',
  'AWS::ApiGateway::Integration', // aws_api_gateway_integration
  'AWS::ApiGateway::IntegrationResponse', // aws_api_gateway_integration_response
  'AWS::ApiGateway::Method',
  'AWS::ApiGateway::MethodResponse',
  'AWS::ApiGateway::Model',
  'AWS::ApiGateway::RequestValidator',
  'AWS::ApiGateway::Resource',
  'AWS::ApiGateway::RestApiPolicy',
  'AWS::ApiGateway::UsagePlan',
  'AWS::ApiGateway::UsagePlanKey',
  'AWS::ApiGateway::VpcLink',
  
  // API Gateway V2
  'AWS::ApiGatewayV2::ApiMapping',
  'AWS::ApiGatewayV2::Authorizer',
  'AWS::ApiGatewayV2::Deployment',
  'AWS::ApiGatewayV2::DomainName',
  'AWS::ApiGatewayV2::Integration',
  'AWS::ApiGatewayV2::IntegrationResponse',
  'AWS::ApiGatewayV2::Model',
  'AWS::ApiGatewayV2::Route',
  'AWS::ApiGatewayV2::RouteResponse',
  'AWS::ApiGatewayV2::Stage',
  'AWS::ApiGatewayV2::VpcLink',
  
  // Application Auto Scaling
  'AWS::ApplicationAutoScaling::ScalingPolicy',
  'AWS::ApplicationAutoScaling::ScheduledAction',
  
  // AppConfig
  'AWS::AppConfig::Extension',
  'AWS::AppConfig::ExtensionAssociation',
  'AWS::AppConfig::HostedConfigurationVersion',
  
  // AppFlow
  'AWS::AppFlow::ConnectorProfile',
  
  // AppIntegrations
  'AWS::AppIntegrations::EventIntegration',
  
  // App Mesh
  'AWS::AppMesh::GatewayRoute',
  'AWS::AppMesh::Mesh',
  'AWS::AppMesh::Route',
  'AWS::AppMesh::VirtualGateway',
  'AWS::AppMesh::VirtualNode',
  'AWS::AppMesh::VirtualRouter',
  'AWS::AppMesh::VirtualService',
  
  // Auto Scaling
  'AWS::AutoScaling::LifecycleHook',
  'AWS::AutoScaling::NotificationConfiguration',
  'AWS::AutoScaling::ScalingPolicy',
  'AWS::EC2::PlacementGroup',
  
  // Backup
  'AWS::Backup::BackupPlan',
  'AWS::Backup::BackupSelection',
  'AWS::Backup::GlobalSettings',
  'AWS::Backup::RegionSettings',
  'AWS::Backup::BackupVaultNotifications',
  'AWS::Backup::BackupVaultPolicy',
  
  // CloudFormation
  'AWS::CloudFormation::StackSet', // aws_cloudformation_stack_set_instance equivalent
  'AWS::CloudFormation::ResourceVersion', // aws_cloudformation_type equivalent
  
  // CloudFront
  'AWS::CloudFront::OriginAccessIdentity', // aws_cloudfront_origin_access_identity
  'AWS::CloudFront::PublicKey',
  
  // CloudWatch Events
  'AWS::Events::Rule',
  'AWS::Events::EventBus',
  
  // CloudWatch Logs (aws_cloudwatch_log_group is PAID - has data ingestion costs!)
  // These are free configuration resources:
  'AWS::Logs::Destination',
  'AWS::Logs::DestinationPolicy',
  'AWS::Logs::MetricFilter',
  'AWS::Logs::ResourcePolicy',
  'AWS::Logs::LogStream',
  'AWS::Logs::SubscriptionFilter',
  
  // CodeBuild
  'AWS::CodeBuild::ReportGroup',
  'AWS::CodeBuild::SourceCredential',
  
  // Config
  'AWS::Config::AggregationAuthorization',
  'AWS::Config::ConfigurationAggregator',
  'AWS::Config::ConfigurationRecorderStatus', // aws_config_configuration_recorder_status
  'AWS::Config::DeliveryChannel',
  'AWS::Config::RemediationConfiguration',
  
  // Customer Gateway
  'AWS::EC2::CustomerGateway',
  
  // RDS/DB
  'AWS::RDS::DBInstanceRoleAssociation', // aws_db_instance_role_association
  'AWS::RDS::OptionGroup',
  'AWS::RDS::DBParameterGroup',
  'AWS::RDS::DBSubnetGroup',
  
  // Default VPC resources
  'AWS::EC2::NetworkAcl', // aws_default_network_acl
  'AWS::EC2::RouteTable', // aws_default_route_table
  'AWS::EC2::SecurityGroup', // aws_default_security_group
  'AWS::EC2::Subnet', // aws_default_subnet
  'AWS::EC2::DHCPOptions', // aws_default_vpc_dhcp_options
  'AWS::EC2::VPC', // aws_default_vpc
  
  // DMS
  'AWS::DMS::ReplicationSubnetGroup',
  'AWS::DMS::ReplicationTask',
  
  // DocumentDB
  'AWS::DocDB::DBClusterParameterGroup',
  'AWS::DocDB::DBSubnetGroup',
  
  // Direct Connect
  'AWS::DirectConnect::BGPPeer', // aws_dx_bgp_peer
  'AWS::DirectConnect::GatewayAssociationProposal', // aws_dx_gateway_association_proposal
  'AWS::DirectConnect::DirectConnectGateway', // aws_dx_gateway
  'AWS::DirectConnect::HostedPrivateVirtualInterfaceAccepter',
  'AWS::DirectConnect::HostedPrivateVirtualInterface',
  'AWS::DirectConnect::HostedPublicVirtualInterfaceAccepter',
  'AWS::DirectConnect::HostedPublicVirtualInterface',
  'AWS::DirectConnect::HostedTransitVirtualInterfaceAccepter',
  'AWS::DirectConnect::HostedTransitVirtualInterface',
  'AWS::DirectConnect::Lag',
  'AWS::DirectConnect::PrivateVirtualInterface',
  'AWS::DirectConnect::PublicVirtualInterface',
  'AWS::DirectConnect::TransitVirtualInterface',
  
  // DynamoDB
  'AWS::DynamoDB::TableItem', // aws_dynamodb_table_item - not a real CFN type but good to have
  
  // EBS
  'AWS::EC2::EncryptionByDefault', // aws_ebs_encryption_by_default
  
  // EC2 Client VPN
  'AWS::EC2::ClientVpnAuthorizationRule',
  'AWS::EC2::ClientVpnRoute',
  
  // EC2 Tags
  'AWS::EC2::Tag', // aws_ec2_tag - not a standard CFN type
  
  // EC2 Traffic Mirror
  'AWS::EC2::TrafficMirrorFilterRule',
  'AWS::EC2::TrafficMirrorFilter',
  'AWS::EC2::TrafficMirrorTarget',
  
  // EC2 Transit Gateway
  'AWS::EC2::TransitGateway', // Free per Infracost
  'AWS::EC2::TransitGatewayPeeringAttachmentAccepter',
  'AWS::EC2::TransitGatewayRouteTable',
  'AWS::EC2::TransitGatewayRouteTableAssociation',
  'AWS::EC2::TransitGatewayRouteTablePropagation',
  'AWS::EC2::TransitGatewayRoute',
  'AWS::EC2::TransitGatewayVpcAttachmentAccepter',
  
  // ECR
  'AWS::ECR::LifecyclePolicy',
  'AWS::ECR::RepositoryPolicy',
  
  // ECS
  'AWS::ECS::AccountSettingDefault',
  'AWS::ECS::CapacityProvider',
  'AWS::ECS::Cluster',
  'AWS::ECS::TaskDefinition',
  
  // Egress Only Internet Gateway
  'AWS::EC2::EgressOnlyInternetGateway',
  
  // EFS
  'AWS::EFS::AccessPoint',
  'AWS::EFS::FileSystemPolicy',
  'AWS::EFS::MountTarget',
  
  // EIP
  'AWS::EC2::EIPAssociation',
  
  // EKS
  'AWS::EKS::Addon',
  'AWS::EKS::IdentityProviderConfig',
  
  // ElastiCache
  'AWS::ElastiCache::ParameterGroup',
  'AWS::ElastiCache::SecurityGroup',
  'AWS::ElastiCache::SubnetGroup',
  'AWS::ElastiCache::User',
  'AWS::ElastiCache::UserGroup',
  'AWS::ElastiCache::UserGroupAssociation',
  
  // Elasticsearch
  'AWS::Elasticsearch::DomainPolicy',
  
  // Elastic Beanstalk
  'AWS::ElasticBeanstalk::Application',
  
  // ELB
  'AWS::ElasticLoadBalancing::LoadBalancerAttachment', // aws_elb_attachment
  
  // Flow Logs
  'AWS::EC2::FlowLog',
  
  // Glue
  'AWS::Glue::Table',
  'AWS::Glue::Classifier',
  'AWS::Glue::Connection',
  'AWS::Glue::DataCatalogEncryptionSettings',
  'AWS::Glue::Partition',
  'AWS::Glue::PartitionIndex',
  'AWS::Glue::Registry',
  'AWS::Glue::ResourcePolicy',
  'AWS::Glue::Schema',
  'AWS::Glue::SecurityConfiguration',
  'AWS::Glue::Trigger',
  'AWS::Glue::UserDefinedFunction',
  'AWS::Glue::Workflow',
  
  // IAM
  'AWS::IAM::AccessKey',
  'AWS::IAM::AccountAlias',
  'AWS::IAM::AccountPasswordPolicy',
  'AWS::IAM::Group',
  'AWS::IAM::GroupPolicy',
  'AWS::IAM::InstanceProfile',
  'AWS::IAM::ManagedPolicy',
  'AWS::IAM::OIDCProvider',
  'AWS::IAM::Policy',
  'AWS::IAM::Role',
  'AWS::IAM::RolePolicy',
  'AWS::IAM::SAMLProvider',
  'AWS::IAM::ServerCertificate',
  'AWS::IAM::ServiceLinkedRole',
  'AWS::IAM::User',
  'AWS::IAM::UserPolicy',
  'AWS::IAM::UserToGroupAddition',
  
  // Internet Gateway
  'AWS::EC2::InternetGateway',
  
  // IoT
  'AWS::IoT::Policy',
  
  // Key Pair
  'AWS::EC2::KeyPair',
  
  // KMS
  'AWS::KMS::Alias',
  'AWS::KMS::Ciphertext',
  'AWS::KMS::Grant',
  
  // Lambda
  'AWS::Lambda::Alias',
  'AWS::Lambda::CodeSigningConfig',
  'AWS::Lambda::EventSourceMapping',
  'AWS::Lambda::EventInvokeConfig',
  'AWS::Lambda::LayerVersion',
  'AWS::Lambda::LayerVersionPermission',
  'AWS::Lambda::Permission',
  
  // Launch Configuration/Template
  'AWS::AutoScaling::LaunchConfiguration',
  'AWS::EC2::LaunchTemplate',
  
  // LB (same as ALB)
  'AWS::ElasticLoadBalancing::LoadBalancerCookieStickinessPolicy',
  
  // Lightsail
  'AWS::Lightsail::Domain',
  'AWS::Lightsail::KeyPair',
  'AWS::Lightsail::StaticIp',
  'AWS::Lightsail::StaticIpAttachment',
  
  // Load Balancer Policies
  'AWS::ElasticLoadBalancing::LoadBalancerPolicy',
  
  // Main Route Table
  'AWS::EC2::MainRouteTableAssociation',
  
  // MQ
  'AWS::AmazonMQ::Configuration',
  
  // MSK
  'AWS::MSK::Configuration',
  
  // Neptune
  'AWS::Neptune::DBClusterParameterGroup',
  'AWS::Neptune::EventSubscription',
  'AWS::Neptune::DBParameterGroup',
  'AWS::Neptune::DBSubnetGroup',
  
  // Network ACL
  'AWS::EC2::NetworkAclEntry',
  
  // Network Interface
  'AWS::EC2::NetworkInterfaceAttachment',
  'AWS::EC2::NetworkInterface',
  
  // Network Firewall
  'AWS::NetworkFirewall::RuleGroup',
  'AWS::NetworkFirewall::FirewallPolicy',
  'AWS::NetworkFirewall::LoggingConfiguration',
  
  // RAM
  'AWS::RAM::PrincipalAssociation',
  'AWS::RAM::ResourceAssociation',
  'AWS::RAM::ResourceShareAccepter',
  'AWS::RAM::ResourceShare',
  
  // RDS Cluster
  'AWS::RDS::DBClusterEndpoint',
  'AWS::RDS::DBClusterParameterGroup',
  
  // Resource Groups
  'AWS::ResourceGroups::Group',
  
  // Route 53 Resolver
  'AWS::Route53Resolver::DNSSECConfig',
  'AWS::Route53Resolver::QueryLoggingConfigAssociation',
  'AWS::Route53Resolver::QueryLoggingConfig',
  'AWS::Route53Resolver::ResolverRuleAssociation',
  'AWS::Route53Resolver::ResolverRule',
  
  // Route 53 Zone Association
  'AWS::Route53::HostedZoneVPCAssociation',
  
  // Route Table
  'AWS::EC2::SubnetRouteTableAssociation',
  'AWS::EC2::Route',
  
  // S3
  'AWS::S3::AccessPoint',
  'AWS::S3::AccountPublicAccessBlock',
  'AWS::S3::BucketPolicy',
  
  // Secrets Manager
  'AWS::SecretsManager::SecretPolicy',
  'AWS::SecretsManager::RotationSchedule',
  'AWS::SecretsManager::SecretTargetAttachment', // aws_secretsmanager_secret_version equivalent
  
  // Security Group
  'AWS::EC2::SecurityGroupIngress',
  'AWS::EC2::SecurityGroupEgress',
  
  // Service Discovery
  'AWS::ServiceDiscovery::Service',
  
  // SES
  'AWS::SES::DomainDKIM',
  'AWS::SES::DomainIdentity',
  
  // SNS
  'AWS::SNS::PlatformApplication',
  'AWS::SNS::TopicPolicy',
  
  // SQS
  'AWS::SQS::QueuePolicy',
  
  // SSM (NOT aws_ssm_parameter - that has costs!)
  'AWS::SSM::Association',
  'AWS::SSM::MaintenanceWindow',
  'AWS::SSM::MaintenanceWindowTarget',
  'AWS::SSM::MaintenanceWindowTask',
  'AWS::SSM::PatchBaseline',
  'AWS::SSM::PatchGroup',
  'AWS::SSM::ResourceDataSync',
  
  // Subnet
  // Already covered by AWS::EC2::Subnet
  
  // Transfer Family
  'AWS::Transfer::Access',
  'AWS::Transfer::SshKey',
  'AWS::Transfer::User',
  
  // Volume Attachment
  'AWS::EC2::VolumeAttachment',
  
  // VPC
  'AWS::EC2::VPCDHCPOptionsAssociation',
  'AWS::EC2::VPCEndpointConnectionNotification',
  'AWS::EC2::VPCEndpointRouteTableAssociation',
  'AWS::EC2::VPCEndpointServiceAllowedPrincipal',
  'AWS::EC2::VPCEndpointService',
  'AWS::EC2::VPCEndpointSubnetAssociation',
  'AWS::EC2::VPCCidrBlock',
  'AWS::EC2::VPCPeeringConnectionAccepter',
  'AWS::EC2::VPCPeeringConnectionOptions',
  'AWS::EC2::VPCPeeringConnection',
  
  // VPN
  'AWS::EC2::VPNConnectionRoute',
  'AWS::EC2::VPNGatewayAttachment',
  'AWS::EC2::VPNGatewayRoutePropagation',
  'AWS::EC2::VPNGateway',
  
  // WAF (classic)
  'AWS::WAF::ByteMatchSet',
  'AWS::WAF::GeoMatchSet',
  'AWS::WAF::IPSet',
  'AWS::WAF::RateBasedRule',
  'AWS::WAF::RegexMatchSet',
  'AWS::WAF::RegexPatternSet',
  'AWS::WAF::RuleGroup',
  'AWS::WAF::Rule',
  'AWS::WAF::SizeConstraintSet',
  'AWS::WAF::SqlInjectionMatchSet',
  'AWS::WAF::XssMatchSet',
  
  // WAFv2
  'AWS::WAFv2::IPSet',
  'AWS::WAFv2::RegexPatternSet',
  'AWS::WAFv2::RuleGroup',
  'AWS::WAFv2::WebACLAssociation',
  'AWS::WAFv2::LoggingConfiguration',
  
  // CDK Metadata (not in Infracost but useful)
  'AWS::CDK::Metadata',
  
  // Custom resources
  'Custom::*',
]);

// Resources that have costs but are difficult to estimate without usage data
export const USAGE_BASED_RESOURCES = new Set([
  'AWS::Lambda::Function',
  'AWS::DynamoDB::Table',
  'AWS::S3::Bucket',
  'AWS::SNS::Topic', // Publishing has costs
  'AWS::SQS::Queue',
  'AWS::ApiGateway::RestApi',
  'AWS::ApiGatewayV2::Api',
  'AWS::StepFunctions::StateMachine',
  'AWS::Kinesis::Stream',
  'AWS::Firehose::DeliveryStream',
  'AWS::CloudFront::Distribution',
  'AWS::Logs::LogGroup', // Data ingestion and storage costs
  'AWS::Glue::Job',
  'AWS::Glue::Crawler',
  'AWS::Athena::WorkGroup',
  'AWS::CodeBuild::Project',
  'AWS::ECR::Repository',
  'AWS::EFS::FileSystem',
  'AWS::WAFv2::WebACL',
  'AWS::WAF::WebACL',
  'AWS::SSM::Parameter', // Has costs for parameter storage and API calls
  'AWS::Route53::RecordSet',
]);

/**
 * Get the last update time of pricing data
 */
export function getPricingDataLastUpdated(): string | null {
  const allPricing = loadPricingData();
  const usEast = allPricing['us-east-1'];
  return usEast?.lastUpdated || null;
}

/**
 * Check if pricing data needs to be updated (older than 7 days)
 */
export function isPricingDataStale(): boolean {
  const lastUpdated = getPricingDataLastUpdated();
  if (!lastUpdated) return true;
  
  const updateDate = new Date(lastUpdated);
  const now = new Date();
  const daysSinceUpdate = (now.getTime() - updateDate.getTime()) / (1000 * 60 * 60 * 24);
  
  return daysSinceUpdate > 7;
}
